### ISSUE TITLE
get_all_tags() return 500 

### ISSUE THREAD

**Issue by kx499** [MISP/PyMISP#139]
Using 2.4.82 version of MISP and most recent version of PyMISP

>>> misp.get_all_tags()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymisp-2.4.81-py2.7.egg/pymisp/api.py", line 1085, in get_all_tags
    r = self._check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/pymisp-2.4.81-py2.7.egg/pymisp/api.py", line 208, in _check_response
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://misp11.xxxxxx.com/tags

**Comment by Rafiot** [comment]
I just did it and it worked for me.

I suspect either a timeout, or an out-of-memory issue. Can you enable debug (pass `debug=True` to `PyMISP`), and look at the logs on the server?

**Comment by kx499** [comment]
Your mention of a time out made me look at the php settings. I bumped up my php settings and it worked. Sorry for the noise.

**Comment by Rafiot** [comment]
No problem, thank you for the feedback :)
