### ISSUE TITLE
Failing test_sample_upload test

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#183]
Just wanted to update the opensuse package, but one test fails:

```
[   28s] ERROR: test_sample_upload (tests.test_offline.TestOffline)
[   28s] ----------------------------------------------------------------------
[   28s] Traceback (most recent call last):
[   28s]   File "/usr/lib/python3.6/site-packages/requests_mock/mocker.py", line 219, in inner
[   28s]     return func(*args, **kwargs)
[   28s]   File "/home/abuild/rpmbuild/BUILD/pymisp-2.4.87/tests/test_offline.py", line 451, in test_sample_upload
[   28s]     upload = pymisp.upload_sample("tmux", "tests/viper-test-files/test_files/tmux", 1)
[   28s]   File "/home/abuild/rpmbuild/BUILD/pymisp-2.4.87/pymisp/api.py", line 831, in upload_sample
[   28s]     to_post['request']['files'] = [{'filename': filename, 'data': self._encode_file_to_upload(filepath_or_bytes)}]
[   28s]   File "/home/abuild/rpmbuild/BUILD/pymisp-2.4.87/pymisp/api.py", line 823, in _encode_file_to_upload
[   28s]     return base64.b64encode(binblob).decode()
[   28s]   File "/usr/lib64/python3.6/base64.py", line 58, in b64encode
[   28s]     encoded = binascii.b2a_base64(s, newline=False)
[   28s] TypeError: a bytes-like object is required, not 'str'
```

**Comment by Rafiot** [comment]
Okay, so that's seriously weird: I had this problem with python 3.4 on travis, but I don't have it on any other python version (2.7, or 3.5 & 3.6), so I blamed python 3.4.

Do you have any idea where it could come from?

**Comment by wagner-certat** [comment]
Did you check with LANG=C ?

It's a common source of encoding errors that there are assumptions about
the default encoding being UTF-8.

**Comment by Rafiot** [comment]
Fixed by that: https://github.com/MISP/PyMISP/commit/05bbfac658fb9f35ab773982b1c7dc94fbdbc96f#diff-0645334504f5c27e7d42e1f0f3cb8d6aR818
