### ISSUE TITLE
examples/add_file_object.py exception handling

### ISSUE THREAD

**Issue by haegardev** [MISP/PyMISP#192]
The following exception is thrown when an elf file is uploaded and if Lief installation is broken.  Exception handling might need a bit of cosmetics.

Traceback (most recent call last):
  File "./add_file_object.py", line 21, in <module>
    fo, peo, seos = make_binary_objects(f)
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/tools/create_misp_object.py", line 54, in make_binary_objects
    standalone=standalone, default_attributes_parameters=default_attributes_parameters)
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/tools/fileobject.py", line 56, in __init__
    self.generate_attributes()
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/tools/fileobject.py", line 59, in generate_attributes
    self.add_attribute('filename', value=self.__filename)
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/mispevent.py", line 999, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/mispevent.py", line 814, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.87.1-py3.6.egg/pymisp/mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.
Traceback (most recent call last):
  File "./add_file_object.py", line 25, in <module>
    if seos:
NameError: name 'seos' is not defined

**Comment by Rafiot** [comment]
There is a lot of things that can go wrong in the `make_binary_objects`: in this case, it was most probably because `describeTypes.json` wasn't up do date, and/or the object definition.

I'm adding a `continue` in case `make_binary_objects` raises an exception so we don't try to upload the objects.
