### ISSUE TITLE
ValueError of response.json() while appending error 

### ISSUE THREAD

**Issue by kar6** [MISP/PyMISP#255]
```
Traceback (most recent call last):
  File "<path>/misp_ipcount.py", line 234, in process
    raise e
  File "<path>/misp_ipcount.py", line 230, in process
    response = self.misp.update_event(event_id=mevent_check['id'], event=mevent)
  File "<path>/git/PyMISP/pymisp/api.py", line 345, in update_event
    return self._check_response(response)
  File "<path>/git/PyMISP/pymisp/api.py", line 214, in _check_response
    errors.append(response.json())
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

could you help me with this error? is it error while parsing response to json? because i had all my parameters right and this error comes not everytime i update my misp-event.

**Comment by Rafiot** [comment]
It probably mean you get either an empty response, or an HTML blob from the server. Can you enable debug (`debug=True` to PyMISP), and give me the output (the last query/answer to/from the server will do)

Be careful, the full output will contain your auth key so don't copy.paste everything in here.

**Comment by kar6** [comment]
thank you for the fast response.

This ist the last DEBUG Entry i could get:

`DEBUG [api.py:156 - __prepare_request() ] {'User-Agent': 'PyMISP 2.4.90 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '17513148', 'Authorization': '<authkey>', 'content-type': 'application/json'}`

i tried to print the response.content and got this:

`response content : b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n'`

you were right with html. how can i handle this error properly?

**Comment by Rafiot** [comment]
Okay, so the webserver, or the (reverse?)proxy is failing somehow. Are you doing lots of queries very fast? What is `misp_ipcount.py` doing?

**Comment by Rafiot** [comment]
Okay, so the webserver, or the (reverse?)proxy is failing somehow. Are you doing lots of queries very fast? What is `misp_ipcount.py` doing?

**Comment by kar6** [comment]
`misp_ipcount.py` uploads the ip attributes and updates their comments. For this case, one misp event could have more than 30000 attributes and reguraly do add and update with around the same amount. It seems that it was always failing while update_event and updated or added just some attributes. Do you had any experience managing misp events with so many attributes using pymisp?
