### ISSUE TITLE
PyMISP search error "the response is not JSON"

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/PyMISP#256]
### Command:
```
>>> response = pymisp.search(controller='events', last='1d', type_attribute='domain')
```

### Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 219, in _check_response
    json_response = response.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 1182, in search
    return self.__query('restSearch/download', query, controller, async_callback)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 1006, in __query
    return self._check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 222, in _check_response
    raise PyMISPError(everything_broken.format(response.request.headers, response.request.body, response.text))
pymisp.exceptions.PyMISPError: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.93 - Python 3.6.5', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '32', 'Authorization': '<API_key>', 'content-type': 'application/json'}
Request body:
{"type": "domain", "last": "1d"}
Response (if any):
```

**Comment by Rafiot** [comment]
The servers doesn't return anything, that's odd. Is the query expected to return something?

It will be fixed by the very soon to come update on the API requests interface. Poke @iglocska :p

**Comment by Rafiot** [comment]
An other thing: is it possible the query returns a lot of events and it reaches the limit allowed to PHP?
