### ISSUE TITLE
PyMISP test connection error + how to add self signed ssl CA

### ISSUE THREAD

**Issue by derbananenkoenig** [MISP/PyMISP#259]
Hey folks, 

i have tried to start to play with the API and configured keys.py with the server address + the api key, set the ssl verification to false and get this error. 

```
user@server:~/MISP/PyMISP/examples$ python3 last.py -l 10
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
CRITICAL [api.py:229 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'Authorization': '<myapikey>', 'Connection': 'keep-alive', 'User-Agent': 'PyMISP 2.4.93 - Python 3.5.2', 'Content-Length': '14', 'Accept': 'application/json', 'content-type': 'application/json', 'Accept-Encoding': 'gzip, deflate'}
Request body:
{"last": "10"}
Response (if any):
{'message': 'An Internal Error Has Occurred.', 'url': '/events/restSearch/download', 'name': 'An Internal Error Has Occurred.'}
No results for that time period

```
```
user@server:~/MISP/PyMISP/examples$ cat keys.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

misp_url = 'https://mymisp.mydomain.com:8443/'
misp_key = '<myapikey>' # The MISP auth key can be found on the MISP web interface under the automation section
misp_verifycert = False
```

Also i have spent quite some time trying to figure out how to get my own root CA certificate to be accepted , so that i could enable the misp_verifycert , could you please explain how i can integrate my own rootCA?

**Comment by Rafiot** [comment]
What happen if you run the following command:
```
python3 last.py -l 10d
```

For the certificate, we use directly python requests, so you have a few options described here: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

**Comment by derbananenkoenig** [comment]
Hi Rafiot, 

The same. I originally wanted to delete all events from the instance and took this idea as a reason to install and test the pymisp api connection. 

Here is the output of your command: 
```
user@server:~/MISP/PyMISP/examples$ python3 last.py -l 10d
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
CRITICAL [api.py:229 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.93 - Python 3.5.2', 'content-type': 'application/json', 'Authorization': 'myAPIKEY', 'Connection': 'keep-alive', 'Content-Length': '15', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate'}
Request body:
{"last": "10d"}
Response (if any):
{'message': 'An Internal Error Has Occurred.', 'name': 'An Internal Error Has Occurred.', 'url': '/events/restSearch/download'}
No results for that time period

```

**Comment by Rafiot** [comment]
So there is an error on MISP side (error 500). Can you look at the logs?

**Comment by derbananenkoenig** [comment]
Allright, it was the php memory_limit that was too low and caused the error. 

The error message was a bit misleading, as i interpreted it as trying to allocate  400M out of 800M free, seems that was not the case. I increased memory_limit and it seems fine. 

for reference here is the error message from Cake

2018-08-16 15:57:46 Error: Fatal Error (1): Allowed memory size of 805306368 bytes exhausted (tried to allocate 474398720 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeResponse.php, line 551]
2018-08-16 15:57:46 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch/download
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 551)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 551, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}


i guess we can close this one
