### ISSUE TITLE
Test fail with current 2.4.95.1: no attribute 'test_offline'

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#274]
```
[   16s] + /usr/bin/python2 setup.py test
[   16s] WARNING [__init__.py:49 - <module>() ] Unable to load pymisp properly: No module named enum
[   16s] running test
[   16s] running egg_info
[   16s] writing requirements to pymisp.egg-info/requires.txt
[   16s] writing pymisp.egg-info/PKG-INFO
[   16s] writing top-level names to pymisp.egg-info/top_level.txt
[   16s] writing dependency_links to pymisp.egg-info/dependency_links.txt
[   16s] reading manifest file 'pymisp.egg-info/SOURCES.txt'
[   16s] reading manifest template 'MANIFEST.in'
[   16s] writing manifest file 'pymisp.egg-info/SOURCES.txt'
[   16s] running build_ext
[   16s] Traceback (most recent call last):
[   16s]   File "setup.py", line 47, in <module>
[   16s]     'data/misp-objects/relationships/definition.json']},
[   16s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
[   16s]     return distutils.core.setup(**attrs)
[   16s]   File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
[   16s]     dist.run_commands()
[   16s]   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
[   16s]     self.run_command(cmd)
[   16s]   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
[   16s]     cmd_obj.run()
[   16s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 228, in run
[   16s]     self.run_tests()
[   16s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 250, in run_tests
[   16s]     exit=False,
[   16s]   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
[   16s]     self.parseArgs(argv)
[   16s]   File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
[   16s]     self.createTests()
[   16s]   File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
[   16s]     self.module)
[   16s]   File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
[   16s]     suites = [self.loadTestsFromName(name, module) for name in names]
[   16s]   File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
[   16s]     parent, obj = obj, getattr(obj, part)
[   16s] AttributeError: 'module' object has no attribute 'test_offline'
```

**Comment by Rafiot** [comment]
There was a missing dependency (enum) in python2 (this is less and less tested, so such things will happen)

**Comment by wagner-certat** [comment]
Is enum required or does it also work with enum34? To cite the [pypi page of enum](https://pypi.org/project/enum/) (emphasis mine):
> Python 3 now has in its standard library an enum implementation (also available for older Python versions as the third-party _enum34_ distribution) that _supersedes this library_.

**Comment by wagner-certat** [comment]
Thanks for f0f3b3f8441bd8b0179ca18b11e1aacaf1d2fc53
