### ISSUE TITLE
PyMISP change_distribution does not work

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/PyMISP#309]
I am getting the error below when attempting to use change_distribution:
```
pymisp.change_distribution(67276, 1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\03415\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\api.py", line 473, in change_distribution
    e = self._make_mispevent(event)
  File "C:\Users\03415\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\api.py", line 274, in _make_mispevent
    e.load(event)
  File "C:\Users\03415\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\mispevent.py", line 461, in load
    if json_event.get('response'):
AttributeError: 'int' object has no attribute 'get'
```

**Comment by robertnixon2003** [comment]
Noticed it was asking for event not event_id
