### ISSUE TITLE
pymisp.search AND-ing tag list support

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#316]
Are there any plans to support for `AND`-ing tag lists in a `pymisp.search()` request (vs. only `OR` support)?

**Comment by Rafiot** [comment]
Yes, it is planned. You can expect it during Q1 or Q2 2019.

**Comment by Rafiot** [comment]
Let's say Q2 :)

**Comment by github-germ** [comment]
Does this line in the 2.4.108 RelNotes mean that this is ready for me to re-test?
* _New logical 'AND' for tag filters has been added in restSearch API._

That'd be great. If so, what's the structure of the PyMISP JSON request?

Thx.

**Comment by Rafiot** [comment]
You can give it a try, yes. It is the same format as `OR`.

**Comment by github-germ** [comment]
@Rafiot ... Nice work. Seems to be working. This will allow us to reduce system resource load for many repeating queries where we had to pull the OR and then filter to AND. Thanks a ton!!!

Btw, just a process question: In general is there a way to associate an issue to a release? Doesn't seem that the release notes list indicates the issue number, and there was no notation in this issue that this was in 2.4.108. Perhaps I'm missing how to correlate. Thx again...

**Comment by github-germ** [comment]
@Rafiot -- how do we use `AND`, `OR`, `NOT` boolean operators with the `tags` argument in `pymisp.search()`?

E.g. this fails:
```
misp.search({'controller': 'attributes',
'type_attribute': 'ip-dst', 
'tags': {'AND': ['admiralty-scale:source-reliability="a"', 'admiralty-scale:information-credibility="1"']}, 
'date_from': 1567453083})
```

with
```
Request headers:
{'User-Agent': 'PyMISP 2.4.114 - Python 3.6.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '176', 'Authorization': 'CtmJMWppkG7l481Lwd1sO48XoO1PhGufhOJntWFW', 'content-type': 'application/json'}
Request body:
{"type": "ip-dst", "tags": [{"AND": ["admiralty-scale:source-reliability=\"a\"", "admiralty-scale:information-credibility=\"1\""]}], "from": 1567452731, "returnFormat": "json"}
Response (if any):
{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/attributes/restSearch'}
search() returned (secs=0.0): {'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/attributes/restSearch', 'errors': ["500 exception: {'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/attributes/restSearch'}"]}
```
and
```
# tail -f --lines=0 error.log
2019-09-03 21:32:11 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= (Array)' at line 1
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('list', Array)
#6 /var/www/MISP/app/Model/Tag.php(252): Model->find('list', Array)
#7 /var/www/MISP/app/Model/Tag.php(203): Tag->findTagIdsByTagNames(Array)
#8 /var/www/MISP/app/Model/Attribute.php(2266): Tag->fetchTagIdsSimple(Array)
#9 /var/www/MISP/app/Model/Event.php(2604): Attribute->set_filter_tags(Array, Array, Array)
#10 /var/www/MISP/app/Model/Attribute.php(4179): Event->set_filter_tags(Array, Array, Array)
#11 /var/www/MISP/app/Model/Attribute.php(4219): Attribute->buildFilterConditions(Array, Array)
#12 /var/www/MISP/app/Controller/AttributesController.php(1924): Attribute->restSearch(Array, 'json', Array, false, false, 0, '')
#13 [internal function]: AttributesController->restSearch()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}
^C
# 
```

**Comment by github-germ** [comment]
Ah... ```ExpandedPyMISP.build_complex_query()``` -- let me play with that.

**Comment by github-germ** [comment]
OK, yes indeed. It works. Excerpt from my test for others to see...

[mispSearchAndOrNot.py.TXT](https://github.com/MISP/PyMISP/files/3575738/mispSearchAndOrNot.py.TXT)

**Comment by Rafiot** [comment]
Can you open a new issue please.
