### ISSUE TITLE
certificate verify failed: self signed certificate (_sslc:1076)

### ISSUE THREAD

**Issue by lemmou** [MISP/PyMISP#454]
I installed manually the misp using the documentation on the ubuntu server.
I used my scripts that work correctly using the misp vm, but using the new installed misp, i have the following error:

`Traceback (most recent call last):
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 368, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.56.102', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\aping.py", line 72, in __init__
    response = self.recommended_pymisp_version
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\aping.py", line 122, in recommended_pymisp_version
    response = self._prepare_request('GET', 'servers/getPyMISPVersion.json')
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\aping.py", line 2102, in _prepare_request
    return s.send(prepped, **settings)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.56.102', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ylemmou\Desktop\Search.py", line 5, in <module>
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
  File "C:\Users\ylemmou\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\aping.py", line 87, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://192.168.56.102/). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='192.168.56.102', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)')))`

**Comment by lemmou** [comment]
It's the same issue mentioned here https://github.com/MISP/PyMISP/issues/134

Thx
