### ISSUE TITLE
Weird message when calling misp.search

### ISSUE THREAD

**Issue by criptk** [MISP/PyMISP#505]
I have a few events that have attributes like "domain|ip" and it think that this maybe related to this:
---
        result = misp.search(limit=LIMIT, org=ORG, pythonify=True,return_format="json",timestamp=events_timestamp)
---

Traceback (most recent call last):
  File "C:/Users/dsantos/PycharmProjects/misp_to_hive/script.py", line 448, in <module>
    main()
  File "C:/Users/dsantos/PycharmProjects/misp_to_hive/script.py", line 310, in main
    result = misp.search(limit=LIMIT, org=ORG, pythonify=True,return_format="json",timestamp=events_timestamp)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\aping.py", line 1542, in search
    me.load(e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 648, in load
    self.from_dict(**event)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 731, in from_dict
    [self.add_object(obj) for obj in kwargs.pop('Object')]
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 731, in <listcomp>
    [self.add_object(obj) for obj in kwargs.pop('Object')]
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 869, in add_object
    **obj)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 1299, in __init__
    self._set_template(kwargs.get('misp_objects_path_custom'))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 1362, in _set_template
    self._known_template = self._load_template_path(self.misp_objects_path / self.name / 'definition.json')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pymisp\mispevent.py", line 1335, in _load_template_path
    self._definition = self._load_json(template_path)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Program Files (x86)\\Python37-32\\lib\\site-packages\\pymisp\\data\\misp-objects\\objects\\domain|ip\\definition.json'

Any pointers ?

**Comment by Rafiot** [comment]
Oh, windows. I never used the API on windows but the path it's trying to access is definitely wrong.

This issue should be solved in January when I finally get to remove all python 2.7 support, and rely on pathlib for building the paths to the object template.

In your case, I'd recommend to either use linux, or give a try with python 3.6+
