### ISSUE TITLE
'Role' error when executing "last.py"

### ISSUE THREAD

**Issue by TotoRafa** [MISP/PyMISP#523]
Hello,

I am sorry if this problem has already been solved but I couldn't find anything on the internet. When I am trying "last.py" example with python3 or python3.7, I get the following error: 
```
/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/pymisp/api.py", line 90, in __init__
    self._current_user, self._current_role, self._current_user_settings = self.get_user(pythonify=True, expanded=True)
  File "/anaconda3/lib/python3.7/site-packages/pymisp/api.py", line 1269, in get_user
    r.from_dict(**user['Role'])
KeyError: 'Role'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "last.py", line 31, in <module>
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert)
  File "/anaconda3/lib/python3.7/site-packages/pymisp/api.py", line 92, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://<misp-url>). Please make sure the API key and the URL are correct (http/https is required): 'Role'  
```
I do not really understand why... I think I am using the right API key (found in "https://<misp-url>/events/automation") and URL. I also set the verification certificate to false.

**Comment by Rafiot** [comment]
Which version of MISP are you using?

**Comment by TotoRafa** [comment]
I am currently using the version : 2.4.119.1

**Comment by Rafiot** [comment]
Sorry, I meant the version of the MISP instance you're querying, not PyMISP.

**Comment by TotoRafa** [comment]
It is the 2.4.115

**Comment by Rafiot** [comment]
Right.

You have two options there: 
1. Update MISP
2. Use an older version of PyMISP (in your case, 2.4.114 -> https://pypi.org/project/pymisp/#history)

**Comment by TotoRafa** [comment]
It is working, thank you !

**Comment by Rafiot** [comment]
You're welcome!
