### ISSUE TITLE
Attribute Error: Create_dummy_event (object has no attribute)

### ISSUE THREAD

**Issue by laostmann** [MISP/PyMISP#598]
Traceback (most recent call last):
  File "create_dummy_event.py", line 23, in <module>
    tools.create_dummy_event(misp)
  File "/Users/user/Desktop/PyMISP/examples/events/tools.py", line 58, in create_dummy_event
    return misp.new_event(0, 4, 0, 'dummy event')
AttributeError: 'PyMISP' object has no attribute 'new_event'

Installed PyMISP pip3 and tried to run an example (create_dummy_event) Error above was displayed upon run

**Comment by Rafiot** [comment]
Right, this example is in fact broken, fixing it now.
