### ISSUE TITLE
add_event is not working

### ISSUE THREAD

**Issue by jagprog5** [MISP/PyMISP#621]
PyMISP version: 2.4.130, MISP version: 2.4.130, python: 3.6.8

When running [examples/create_events.py](https://github.com/MISP/PyMISP/blob/main/examples/create_events.py):

`./create_events.py -d0 -a0 -t0 -i"Test info"`

```
Traceback (most recent call last):
  File "./create_events.py", line 25, in <module>
    event = misp.add_event(event, pythonify=True)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 288, in add_event
    e.load(new_event)
  File "/usr/local/lib/python3.6/site-packages/pymisp/mispevent.py", line 1159, in load
    self.from_dict(**event)
  File "/usr/local/lib/python3.6/site-packages/pymisp/mispevent.py", line 1199, in from_dict
    raise NewEventError('The info field of the new event is required.')
pymisp.exceptions.NewEventError: The info field of the new event is required.
```

In `create_events.py` if the arg to `add_event` is changed so that `pythonify=False`, then I get:
``` json
{
    "name": "/events/add API description",
    "description": "POST a MISP Event JSON to this API to create an Event. Contained objects can also be included (such as attributes, objects, tags, etc).",
    "mandatory_fields": ["info"],  
    "optional_fields": ["threat_level_id", "analysis", "distribution", "sharing_group_id", "uuid", "published", "timestamp", "date", 
    "Attribute", "Object", "Shadow_Attribute", "EventTag"],  
    "url": "/events/add"
}
```

The above is what would print out when sending a GET to /events/add on MISP. Weird.

I see in [api.py](https://github.com/MISP/PyMISP/blob/main/pymisp/api.py#L288), that this does not look like an expected response in which to create a returned misp event.

**Comment by Rafiot** [comment]
There are two issues there:
1. you need a space after the `-i`
2. threat_level_id can only be between 1 and 4 

This command will work:
`./create_events.py -d0 -a0 -t1 -i "Test info"`

**Comment by jagprog5** [comment]
`./create_events.py -d0 -a0 -t1 -i "Test info"`

Same results.

A space is not required for arg parser.

**Comment by Rafiot** [comment]
I'm not sure what you mean, you're right that the space is not needed, but `./create_events.py -d0 -a0 -t1 -i"Test info"` works for me.

**Comment by jagprog5** [comment]
Proxy issue, not related to pymisp.

I'd recommend changing the error message to emphasize that the error came from the server's responded event, and not the event that was passed in as an arg. Although, this can be learned by following the stack trace, it's not immediately obvious.

Here's a revised function:

```python
def add_event(self, event: MISPEvent, pythonify: bool = False) -> Union[Dict, MISPEvent]:
        '''Add a new event on a MISP instance'''
        r = self._prepare_request('POST', 'events/add', data=event)
        new_event = self._check_json_response(r)
        if not (self.global_pythonify or pythonify) or 'errors' in new_event:
            return new_event
        e = MISPEvent()
        try:
            e.load(new_event)
            return e
        except NewEventError: # Add import: from .exceptions import NewEventError
            raise MISPServerError(f'Received {r.status_code} status, but response was not a properly formatted misp event:\n{new_event}')
```

If I run the script, while keeping the proxy issue, I now get the trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 289, in add_event
    e.load(new_event)
  File "/usr/local/lib/python3.6/site-packages/pymisp/mispevent.py", line 1159, in load
    self.from_dict(**event)
  File "/usr/local/lib/python3.6/site-packages/pymisp/mispevent.py", line 1199, in from_dict
    raise NewEventError('The info field of the new event is required.')
pymisp.exceptions.NewEventError: The info field of the new event is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tmp.py", line 25, in <module>
    event = misp.add_event(event, pythonify=True)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 292, in add_event
    raise MISPServerError(f'Received {r.status_code} status, but response was not a properly formatted misp event:\n{new_event}')
pymisp.exceptions.MISPServerError: Received 200 status, but response was not a properly formatted misp event:
{'name': '/events/add API description', 'description': 'POST a MISP Event JSON to this API to create an Event. Contained objects can also be included (such as attributes, objects, tags, etc).', 'mandatory_fields': ['info'], 'optional_fields': ['threat_level_id', 'analysis', 'distribution', 'sharing_group_id', 'uuid', 'published', 'timestamp', 'date', 'Attribute', 'Object', 'Shadow_Attribute', 'EventTag'], 'url': '/events/add'}
```
@Rafiot
