### ISSUE TITLE
pymisp.feeds(pythonify=True) JSONDecodeError

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#625]
2.4.131

With 2.4.131 `pymisp.feeds` with `pythonify=True` is throwing `JSONDecodeError`. Perhaps I am missing something. As always, thanks for your help!!

```
(Pdb) f1 = misp.feeds()
(Pdb) len(f1)
78
(Pdb) pp(f1[0])
{'Feed': {'cache_timestamp': '1599710734',
          'caching_enabled': True,
          'default': True,
          'delete_local_file': False,
          'delta_merge': True,
          'distribution': '4',
          'enabled': True,
          'event_id': '0',
          'fixed_event': True,
          'force_to_ids': False,
          'headers': None,
          'id': '1',
          'input_source': 'network',
          'lookup_visible': True,
          'name': 'CIRCL',
          'orgc_id': '0',
          'override_ids': False,
          'provider': 'CIRCL',
          'publish': True,
          'rules': None,
          'settings': '[]',
          'sharing_group_id': '13',
          'source_format': 'misp',
          'tag_id': '1388',
          'url': 'https://www.circl.lu/doc/misp/feed-osint'},
 'Tag': {'colour': '#7de9de',
         'exportable': True,
         'hide_tag': False,
         'id': '1388',
         'name': 'Unvetted',
         'numerical_value': None,
         'org_id': '0',
         'user_id': '0'}}
(Pdb)
(Pdb) f2 = misp.feeds(pythonify=True)
*** json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
(Pdb)
```

**Comment by github-germ** [comment]
We upgraded directly from 2.4.125, where it was working, to 2.4.131. Not sure exactly where it broke.

**Comment by Rafiot** [comment]
This is very weird, the tests cases on that same call are passing and I cannot reproduce it.

ca you do pp(f1) instead?

**Comment by github-germ** [comment]
[pymispIssue625.py.gz](https://github.com/MISP/PyMISP/files/5209136/pymispIssue625.py.gz)

**Comment by github-germ** [comment]
```
$ ./pymispIssue625.py url key
misp={'version': '2.4.131', 'perm_sync': True, 'perm_sighting': True}
pymisp={'version': '2.4.131'}
........pythonify=False........
len(r)=78
r[0]={
  "Feed": {
    "id": "1",
    "name": "CIRCL",
    "provider": "CIRCL",
    "url": "https://www.circl.lu/doc/misp/feed-osint",
    "rules": null,
    "enabled": true,
    "distribution": "4",
    "sharing_group_id": "13",
    "tag_id": "1388",
    "default": true,
    "source_format": "misp",
    "fixed_event": true,
    "delta_merge": true,
    "event_id": "0",
    "publish": true,
    "override_ids": false,
    "settings": "[]",
    "input_source": "network",
    "delete_local_file": false,
    "lookup_visible": true,
    "headers": null,
    "caching_enabled": true,
    "force_to_ids": false,
    "orgc_id": "0",
    "cache_timestamp": "1599797108"
  },
  "Tag": {
    "id": "1388",
    "name": "Unvetted",
    "colour": "#7de9de",
    "exportable": true,
    "org_id": "0",
    "hide_tag": false,
    "user_id": "0",
    "numerical_value": null
  }
}

........pythonify=True........
Exception pythonify=True: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
$ 
```

**Comment by github-germ** [comment]
Hmmm... Looks like something might be installed incorrectly with our upgrade from 2.5.131 to 2.4.131 based on this traceback excerpt revealing 2.4.131. **OUCH**. Likely our issue!!
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py"
```

**Comment by github-germ** [comment]
> Hmmm... Looks like something might be installed incorrectly with our upgrade from 2.5.125 to 2.4.131 based on this traceback excerpt revealing 2.4.131. **OUCH**. Likely our issue!!
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py"
> ```

NVM my last post. I NEED COFFEE. OMG.

**Comment by github-germ** [comment]
[pymispIssue625.py.gz](https://github.com/MISP/PyMISP/files/5209279/pymispIssue625.py.gz)

**Comment by github-germ** [comment]
OK, better code showing traceback. Sorry about my caffeine-lacking prior posts...

```
$ python3 ./pymispTracebackIssue625.py url key
misp={'version': '2.4.131', 'perm_sync': True, 'perm_sighting': True}
pymisp={'version': '2.4.131'}

........pythonify=False........
len(r)=78
r[0]={
  "Feed": {
    "id": "1",
    "name": "CIRCL",
    "provider": "CIRCL",
    "url": "https://www.circl.lu/doc/misp/feed-osint",
    "rules": null,
    "enabled": true,
    "distribution": "4",
    "sharing_group_id": "13",
    "tag_id": "1388",
    "default": true,
    "source_format": "misp",
    "fixed_event": true,
    "delta_merge": true,
    "event_id": "0",
    "publish": true,
    "override_ids": false,
    "settings": "[]",
    "input_source": "network",
    "delete_local_file": false,
    "lookup_visible": true,
    "headers": null,
    "caching_enabled": true,
    "force_to_ids": false,
    "orgc_id": "0",
    "cache_timestamp": "1599797108"
  },
  "Tag": {
    "id": "1388",
    "name": "Unvetted",
    "colour": "#7de9de",
    "exportable": true,
    "org_id": "0",
    "hide_tag": false,
    "user_id": "0",
    "numerical_value": null
  }
}

........pythonify=True........
Traceback (most recent call last):
  File "./pymispTracebackIssue625.py", line 20, in <module>
    r = misp.feeds(pythonify=pythonify)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py", line 948, in feeds
    f.from_dict(**feed)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/mispevent.py", line 1532, in from_dict
    self.settings = json.loads(self.settings)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
$ 
```

**Comment by github-germ** [comment]
[pymispTracebackIssue625.py.gz](https://github.com/MISP/PyMISP/files/5209296/pymispTracebackIssue625.py.gz)

**Comment by github-germ** [comment]
APPARENTLY, root cause was invalid JSON in a `feeds.settings`, i.e. BAD data.

Case closed. UG!

**Comment by chrisinmtown** [comment]
I suggest the following change to mispevent.py, if you agree I'll see about submitting a PR:

```
@@ -1529,7 +1528,11 @@ class MISPFeed(AbstractMISP):
             kwargs = kwargs['Feed']
         super().from_dict(**kwargs)
         if hasattr(self, 'settings'):
-            self.settings = json.loads(self.settings)
+            try:
+                self.settings = json.loads(self.settings)
+            except json.decoder.JSONDecodeError:
+                logger.exception("Failed to parse feed settings: {}".format(self.settings))
+                raise
```

**Comment by Rafiot** [comment]
Good point, that would be a lot less confusing.

Feel free to do a PR if you already have the code at hand. Otherwise, I'll take care of it in the next few days.

**Comment by chrisinmtown** [comment]
This also needs a proper test case. I think you will implement that before I do, so please go ahead if you can find the time.
