### ISSUE TITLE
PyMISP tags() method results in server error with code 500

### ISSUE THREAD

**Issue by cudor** [MISP/PyMISP#638]
With the PyMISP tags() method I want to get a list of all tags in my MISP instance. This always results in a server error with code 500, although I can access the URL https://mymisp.example.org/tags/index with a browser without any issues.

This is the output of the Python script:
```CRITICAL [api.py:2436 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.131 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': '***auth_key***', 'content-type': 'application/json'}
Request body:
None
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/tags\/index"}
Traceback (most recent call last):
  File "ciso-scorecard.py", line 42, in <module>
    list_of_tags = misp.tags()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymisp/api.py", line 654, in tags
    tags = self._check_json_response(r)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymisp/api.py", line 2428, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymisp/api.py", line 2437, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/tags\/index"}```

This happens with MISP server versions 2.4.131 and 2.4.132.

Side question: Is it possible with PyMISP to search for tags containing a certain string, like e.g. https://mymisp.example.org/tags/index/searchall:veris ?

**Comment by chrisinmtown** [comment]
Just guessing here, but I think you might have some bad data lurking among your system's tags & usages. Unfortunately the tags table doesn't have a created or last-modified field that might let you easily search for new additions or changes.

**Comment by Rafiot** [comment]
@cudor can you check in the logs (`app/tmp/logs/`) if there is anything?

It may be a memory exhaustion issue. @iglocska @mokaddem any idea?

**Comment by cudor** [comment]
@Rafiot Unfortunately, none of the log files in `app/tmp/logs/` gets updated/written to when the tags() method fails. Is there anything else that I can check on the MISP server?

**Comment by mokaddem** [comment]
I also suspect a memory issue, but the fact that @cudor do not have any entry in the logs is weird.
@cudor, not sure if it will help but could you try to pass the parameter `exclude_statistics:1`? It removes some of the data

**Comment by cudor** [comment]
My bad! I was looking at the log files of the wrong MISP instance. ☹️ 

You are correct that it is a memory issue. These are the messages in MISP's error log. @mokaddem The issue is the same with the `exclude_statistics:1` parameter.

```
2020-11-05 17:05:50 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 260046856 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
2020-11-05 17:05:50 Error: [InternalErrorException] Internal Server Error
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```
 
```
2020-11-05 17:08:00 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 247463944 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
2020-11-05 17:08:00 Error: [InternalErrorException] Internal Server Error
Request URL: /tags/index?exclude_statistics=1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by mokaddem** [comment]
@cudor, the URL is actually `/tags/index/exclude_statistics:1` ;)

**Comment by cudor** [comment]
@mokaddem, same response with the correct URL:
```
2020-11-10 16:29:39 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 247463944 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
2020-11-10 16:29:39 Error: [InternalErrorException] Internal Server Error
Request URL: /tags/index/exclude_statistics:1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 502, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by mokaddem** [comment]
@cudor are you on the latest version of MISP? The `exclude_statistics` parameter was added not so long ago, so I'm just making sure ;)

**Comment by Rafiot** [comment]
@mokaddem is this parameter also supported as a POST, or is it only a GET?

**Comment by cudor** [comment]
> @cudor are you on the latest version of MISP? The `exclude_statistics` parameter was added not so long ago, so I'm just making sure ;)

We're on a relatively recent version, 2.4.132, but not on the latest. I didn't realize that the parameter has been introduced in the latest version only. We'll have to check again after an upgrade.

**Comment by cudor** [comment]
> @cudor are you on the latest version of MISP? The `exclude_statistics` parameter was added not so long ago, so I'm just making sure ;)

After an upgrade to 2.4.134, both URLs `/tags/index/` and `/tags/index/exclude_statistics:1` don't run into a memory issue anymore. The `exclude_statistics` URL seems to deliver the response faster, though.

I'm going to close this issue now. Thanks for your support.
