### ISSUE TITLE
Object references cause get_event() fail

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#640]
Hi guys!

We have encountered a bug in PyMISP's `get_event` method (with pythonify=True) for a specific event.

This event uses Object References and this is causing the error. I couldn't really reproduce this with some crafted event 
(the errored one can't be shared here).

Screenshot from the event:

![misp_misbehaving_event](https://user-images.githubusercontent.com/32512488/96448682-0eb01a00-1214-11eb-8ce1-2c2f19e1110a.PNG)

**Post-mortem stacktrace:**

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/pdb.py", line 1704, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/usr/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/administrator/git/misp-g2-enricher/misp_g2_enricher.py", line 384, in <module>
    run_forever()
  File "/home/administrator/git/misp-g2-enricher/misp_g2_enricher.py", line 355, in run_forever
    updated_events_ids, valid_responses_count = submit_g2_data_to_misp(misp)
  File "/home/administrator/git/misp-g2-enricher/misp_g2_enricher.py", line 167, in submit_g2_data_to_misp
    event_to_update = misp.get_event(event_id, pythonify=True)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 278, in get_event
    e.load(event_r)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 1159, in load
    self.from_dict(**event)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 1252, in from_dict
    [self.add_object(obj) for obj in kwargs.pop('Object')]
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 1252, in <listcomp>
    [self.add_object(obj) for obj in kwargs.pop('Object')]
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 1393, in add_object
    misp_obj.from_dict(**obj)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 813, in from_dict
    [self.add_reference(**r) for r in kwargs.pop('ObjectReference')]
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 813, in <listcomp>
    [self.add_reference(**r) for r in kwargs.pop('ObjectReference')]
  File "/usr/local/lib/python3.8/dist-packages/pymisp/mispevent.py", line 837, in add_reference
    reference.from_dict(object_uuid=object_uuid, referenced_uuid=referenced_uuid,
TypeError: from_dict() got multiple values for keyword argument 'object_uuid'
Uncaught exception. Entering post mortem debugging

```

I tried the `get_event` method without the `pythonify=True`, and that works.

Do you have an idea how to fix this?

Thanks!

**Comment by Rafiot** [comment]
Can you just share the ObjectReference that makes the script fail? Because that should really not happen.

**Comment by sustefil** [comment]
Hi @Rafiot, as we found another event triggering this bug, I am getting back to this.

Let me share the complete event here. (just rename .txt to .json)

[pymisp-bug-object-references.txt](https://github.com/MISP/PyMISP/files/5516024/pymisp-bug-object-references.txt)

If you call `get_event` with `pythonify=True`, you will get the error.

Thanks

**Comment by Rafiot** [comment]
Right. For some reason, the `object_uuid'` is None. We're investigating.

**Comment by Rafiot** [comment]
Okay, the issue is fixed, it is weird and I'm curious how it could happen, but in the meantime, the event can be loaded by PyMISP.

The next release of PyMISP will contain the fix.

**Comment by sustefil** [comment]
Thanks, I "cherry-picked" the fix for now.
