### ISSUE TITLE
Error when adding attributes as a list, where the list contains one item.

### ISSUE THREAD

**Issue by tlansec** [MISP/PyMISP#655]
Hello,

Not sure if best fixed on this side or on the MISP itself side, but essentially I want to write code where it works regardless of the # of attributes, so i'm using a list that contains an attribute per item. When there is only one item in the list PyMISP does not parse the response from MISP correctly. 

Example code, run using Python 3.7.8 on PyMISP 2.4.134:

```
from pymisp import ExpandedPyMISP, MISPAttribute
 
# define misp url, key, cert here

m = ExpandedPyMISP(misp_url, misp_key, misp_verifycert) # Needs fixing for your local misp

domains = ['foobar3.com']
some_existing_event_id = 510 # need replacing with an existing event 

attributes = []
for d in domains:
    this_attr = MISPAttribute()
    this_attr.value = d 
    this_attr.type = 'domain'
    attributes.append(this_attr)

added_attributes = m.add_attribute(some_existing_event_id, attributes, pythonify=True)
```

The response from the server for this similar to the following:

```
{'Attribute': {'id': '12891', 'event_id': '510', 'object_id': '0', 'object_relation': None, 'category': 'Network activity', 'type': 'domain', 'value1': 'foobar3.com', 'value2': '', 'to_ids': True, 'uuid': '543e3808-2df2-4b7b-aee0-a0c54c0b7e33', 'timestamp': '1604937840', 'distribution': '5', 'sharing_group_id': '0', 'comment': '', 'deleted': False, 'disable_correlation': False, 'first_seen': None, 'last_seen': None, 'value': 'foobar3.com'}, 'AttributeTag': []}
```

Since 'Attribute' is not a list but the input value was a list, this will yield the following error:

```
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    added_attributes = m.add_attribute(some_existing_event_id, attributes, pythonify=True)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python37\lib\site-packages\pymisp\api.py", line 557, in add_attribute
    a.from_dict(**new_attr)
TypeError: from_dict() argument after ** must be a mapping, not str
```

Let me know if this doesn't make sense or if you need any additional examples. I would have perhaps attempted a PR, but I'm not sure whether the best design decision is to alter the response on the misp side or to fix the parsing on the PyMISP side (although I expect it is the latter).

Cheers,
Tom

**Comment by Rafiot** [comment]
Woops, good catch. Yeah, I totally forgot about that feature. Just making sure, if the list you send has more than one entry, it works fine? It will teach me to have a feature without a test case ;)

If you feel like making a PR, go for it, and if you also feel like updating the tests cases, even better. Otherwise, I'll get it sorted this week.

**Comment by tlansec** [comment]
If the list you send has more than one entry it will always work because the response contains a list of attributes instead of just one.

I might have a crack at the PR tomorrow.

**Comment by chrisinmtown** [comment]
When you fix this, I suggest updating the signature and docstring to:
```
    def add_attribute(self, event: Union[MISPEvent, int, str, UUID], attribute: Union[MISPAttribute, list], pythonify: bool = False) -> Union[Dict, MISPAttribute, MISPShadowAttribute]:
        """Add an attribute to an existing MISP event

        :param event: event to extend
        :param attribute: attribute or (MISP version 2.4.113+) list of attributes to add.
            If a list is passed, the pythonified response is a dict with the following structure:
            {'attributes': [MISPAttribute], 'errors': {errors by attributes}}
        :param pythonify: Returns a PyMISP Object instead of the plain json output
        """
```

**Comment by chrisinmtown** [comment]
I propose the following change including docstring update:
```
-    def add_attribute(self, event: Union[MISPEvent, int, str, UUID], attribute: MISPAttribute, pythonify: bool = False) -> Union[Dict, MISPAttribute, MISPShadowAttribute]:
+    def add_attribute(self, event: Union[MISPEvent, int, str, UUID], attribute: Union[MISPAttribute, list], pythonify: bool = False) -> Union[Dict, MISPAttribute, MISPShadowAttribute]:
         """Add an attribute to an existing MISP event
 
         :param event: event to extend
-        :param attribute: attribute to add.  NOTE MISP 2.4.113+: you can pass a list of attributes.
-            In that case, the pythonified response is the following: {'attributes': [MISPAttribute], 'errors': {errors by attributes}}
+        :param attribute: attribute or (MISP version 2.4.113+) list of attributes to add.
+            If a list is passed, the pythonified response is a dict with the following structure:
+            {'attributes': [MISPAttribute], 'errors': {errors by attributes}}
         :param pythonify: Returns a PyMISP Object instead of the plain json output
         """
         event_id = get_uuid_or_id_from_abstract_misp(event)
@@ -582,10 +583,15 @@ class PyMISP:
             if 'errors' in new_attribute:
                 to_return['errors'] = new_attribute['errors']
 
-            for new_attr in new_attribute['Attribute']:
+            if len(attribute) == 1:
+                # input list size 1 yields dict, not list with single dict
                 a = MISPAttribute()
-                a.from_dict(**new_attr)
-                to_return['attributes'].append(a)
+                a.from_dict(**new_attribute['Attribute'])
+            else:
+                for new_attr in new_attribute['Attribute']:
+                    a = MISPAttribute()
+                    a.from_dict(**new_attr)
+                    to_return['attributes'].append(a)
             return to_return
 
         if ('errors' in new_attribute and new_attribute['errors'][0] == 403
```

**Comment by chrisinmtown** [comment]
Sorry that previous patch didn't handle error cases.  Here's a better one.
```
diff --git a/pymisp/api.py b/pymisp/api.py
index 5b5caab..6fceaef 100644
--- a/pymisp/api.py
+++ b/pymisp/api.py
@@ -563,12 +563,13 @@ class PyMISP:
         r = self._prepare_request('HEAD', f'attributes/view/{attribute_id}')
         return self._check_head_response(r)
 
-    def add_attribute(self, event: Union[MISPEvent, int, str, UUID], attribute: MISPAttribute, pythonify: bool = False) -> Union[Dict, MISPAttribute, MISPShadowAttribute]:
+    def add_attribute(self, event: Union[MISPEvent, int, str, UUID], attribute: Union[MISPAttribute, list], pythonify: bool = False) -> Union[Dict, MISPAttribute, MISPShadowAttribute]:
         """Add an attribute to an existing MISP event
 
         :param event: event to extend
-        :param attribute: attribute to add.  NOTE MISP 2.4.113+: you can pass a list of attributes.
-            In that case, the pythonified response is the following: {'attributes': [MISPAttribute], 'errors': {errors by attributes}}
+        :param attribute: attribute or (MISP version 2.4.113+) list of attributes to add.
+            If a list is passed, the pythonified response is a dict with the following structure:
+            {'attributes': [MISPAttribute], 'errors': {errors by attributes}}
         :param pythonify: Returns a PyMISP Object instead of the plain json output
         """
         event_id = get_uuid_or_id_from_abstract_misp(event)
@@ -582,10 +583,17 @@ class PyMISP:
             if 'errors' in new_attribute:
                 to_return['errors'] = new_attribute['errors']
 
-            for new_attr in new_attribute['Attribute']:
-                a = MISPAttribute()
-                a.from_dict(**new_attr)
-                to_return['attributes'].append(a)
+            if len(attribute) == 1:
+                # input list size 1 yields dict, not list of size 1
+                if 'Attribute' in new_attribute:
+                    a = MISPAttribute()
+                    a.from_dict(**new_attribute['Attribute'])
+                    to_return['attributes'].append(a)
+            else:
+                for new_attr in new_attribute['Attribute']:
+                    a = MISPAttribute()
+                    a.from_dict(**new_attr)
+                    to_return['attributes'].append(a)
             return to_return
 
         if ('errors' in new_attribute and new_attribute['errors'][0] == 403
```

**Comment by chrisinmtown** [comment]
And I propose this extension to the test cases:
```
diff --git a/tests/testlive_comprehensive.py b/tests/testlive_comprehensive.py
index b2f44df..6263710 100644
--- a/tests/testlive_comprehensive.py
+++ b/tests/testlive_comprehensive.py
@@ -1650,6 +1650,13 @@ class TestComprehensive(unittest.TestCase):
             self.assertEqual(similar_error['errors'][1]['errors']['value'][0], 'A similar attribute already exists for this event.')
 
             # Test add multiple attributes at once
+            attr0 = MISPAttribute()
+            attr0.value = '0.0.0.0'
+            attr0.type = 'ip-dst'
+            response = self.user_misp_connector.add_attribute(first, [attr0])
+            self.assertTrue(isinstance(response['attributes'], list), response['attributes'])
+            self.assertEqual(response['attributes'][0].value, '0.0.0.0')
+            time.sleep(5)
             attr1 = MISPAttribute()
             attr1.value = '1.2.3.4'
             attr1.type = 'ip-dst'
```

**Comment by Rafiot** [comment]
Excellent, thank you very much, it is merged.

**Comment by chrisinmtown** [comment]
Thanks, then I think you should close this issue!

**Comment by Rafiot** [comment]
I just need to fix the typing issue (will do today), and then I close this one. Thank you again!

**Comment by chrisinmtown** [comment]
please educate me, what typing issue?

**Comment by Rafiot** [comment]
That was the error: https://github.com/MISP/PyMISP/runs/1447742159?check_suite_focus=true#step:7:56

And here is the fix: https://github.com/MISP/PyMISP/commit/7b2e78246a231ce1bcba0a398395306900268566

The typing metadata help to know which kind of datatype we're expecting for each method, and it supposed to be displayed on the sphinx documentation: https://pymisp.readthedocs.io/en/latest/modules.html#pymisp
But it seems broken right now. I'll fix it now.

**Comment by chrisinmtown** [comment]
if everything is fixed, maybe close this?

**Comment by Rafiot** [comment]
Yep, thanks!
