### ISSUE TITLE
PyMISP function search_logs use of args limit, page causes 500 internal server error unknown column

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#680]
I am using MISP version 2.4.133 client and server.  I can search the logs table and get a very large result set.  Then I tried to set a limit on the result size, and the result is an internal server error:
```
2021-01-12 15:37:50 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Log.limit' in 'where clause'
Request URL: /admin/logs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Log`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Log`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Log`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Log), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Controller/LogsController.php(119): Model->find('all', Array)
#7 [internal function]: LogsController->admin_index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(LogsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(LogsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

```

Please run the script below to reproduce the error.
```
#!/usr/bin/env python3
import urllib3
from pymisp import PyMISP

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(url='https://misp.my-company.com:48752', key='mykey', ssl=False)
response = misp.search_logs(model='Attribute', action='add', limit=10, pythonify=False)
print("Response size={}".format(len(response)))
for log in response:
    for key in log:
        print("\t{}={}".format(key, log[key]))
```

Please tell me, am I doing something wrong or is this a genuine bug?

**Comment by chrisinmtown** [comment]
Thanks @PROTechThor for adding a tag but I think this is more appropriately tagged "possible bug" and "needs triage".

**Comment by chrisinmtown** [comment]
Thanks @JakubOnderka for doing the repair over in MISP, I see now that I opened this issue in the wrong repo. Should I move it to the MISP repo?

**Comment by chrisinmtown** [comment]
I think this is fixed now that https://github.com/MISP/MISP/pull/6860 has been merged - will someone please confirm and close this if so?

**Comment by Rafiot** [comment]
Confirmed, it works as expected now: https://github.com/MISP/PyMISP/commit/e93337e75cb2b95c6407645f73e4b73032a1a51c

**Comment by chrisinmtown** [comment]
Glad to see the new automated test, should I close this?

**Comment by Rafiot** [comment]
I meant to close with the last comment, doing it now :)
