### ISSUE TITLE
add_feed.py error

### ISSUE THREAD

**Issue by chaowu2009** [MISP/PyMISP#696]
(base) C02WJ1QVHTDG:examples chaowu$ python add_feed.py -f misp -u 0.0.0.0 -n "test" -i local -p "simulation"
CRITICAL [create_misp_object.py:24 - <module>() ] You need lief >= 0.11.0. The quick and dirty fix is: pip3 install --force pymisp[fileobjects]
INFO [api.py:150 - __init__() ] To configure logging in your script, leave it to None and use the following: import logging; logging.getLogger('pymisp').setLevel(logging.DEBUG)
DEBUG [api.py:3231 - _prepare_request() ] GET - servers/getPyMISPVersion.json
DEBUG [api.py:3233 - _prepare_request() ] {}
Traceback (most recent call last):
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/pymisp/api.py", line 154, in __init__
    response = self.recommended_pymisp_version
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/pymisp/api.py", line 210, in recommended_pymisp_version
    response = self._prepare_request('GET', 'servers/getPyMISPVersion.json')
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/pymisp/api.py", line 3245, in _prepare_request
    prepped = self.__session.prepare_request(req)
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "add_feed.py", line 17, in <module>
    pm = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=True)
  File "/Users/chaowu/Software/Annaconda/anaconda3/lib/python3.8/site-packages/pymisp/api.py", line 175, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (0.0.0.0). Please make sure the API key and the URL are correct (http/https is required): Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?

**Comment by Rafiot** [comment]
it seems that you're passing `0.0.0.0` as a URL for your MISP instance, and as per the error message, it doesn't work: `Please make sure the API key and the URL are correct (http/https is required): Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?`

**Comment by chaowu2009** [comment]
here is my misp_url = 'http://0.0.0.0/'. 
I am sure the API key is correct.

**Comment by Rafiot** [comment]
I'm unsure `0.0.0.0` will work, but it may. You may want to try with localhost, 127.0.0.1, or the IP of the VM if you're using a virtual machine.

The error message above doesn't mention the `http://`: `Unable to connect to MISP (0.0.0.0).`
