### ISSUE TITLE
PyMISP wrongly assumes there is always a patch number in urllib3

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#698]
We encoutered an error when installing PyMISP 2.4.137.3, throwing this error upon creating the PyMISP object:

```python
Traceback (most recent call last): File "test2.py", line 6, in <module> misp = pymisp.PyMISP('https://127.0.0.1', 'nothingtoseehere', ssl=False, debug=False) File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 142, in __init__ if brotli_supported(): File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 97, in brotli_supported major, minor, patch = urllib3.__version__.split('.') # noqa: F811 ValueError: not enough values to unpack (expected 3, got 2)
```

and we had an urllib3 version `1.22`

**Comment by Rafiot** [comment]
thank you !
