### ISSUE TITLE
search() with return_format 'text' returns JSONDecodeError

### ISSUE THREAD

**Issue by marjatech** [MISP/PyMISP#705]
When doing a search with return_format = 'text', PyMISP tries to verify it with _check_json_response(), which will fail.

Think there are already exclusions for return_formats csv, xml etc. text should be there too.

**Comment by chrisinmtown** [comment]
Here's sample code to demonstrate.  Works great with json, xml etc. but not text.  Please add an automated test case for this!!
```
#!/usr/bin/env python3
import urllib3
from pymisp import PyMISP

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(
    url      = 'https://my-company.com:12345',
    key      = 'my-key',
    ssl      = False)
info='my event info)'
response = misp.search(eventinfo=info, return_format='text', pythonify=False)
print("Response size={}".format(len(response)))
for event in response:
    for key in event:
        print("\t{}={}".format(key, event[key]))
```
Here's the error:
```
Traceback (most recent call last):
  File "/Users/me/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/api.py", line 3196, in _check_response
    response_json = response.json()
  File "/Users/me/.virtualenvs/py36/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "searchEventByInfo.py", line 11, in <module>
    response = misp.search(eventinfo=info, return_format='text', pythonify=False)
  File "/Users/me/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/api.py", line 2227, in search
    normalized_response = self._check_json_response(response)
  File "/Users/me/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/api.py", line 3164, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/Users/me/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/api.py", line 3206, in _check_response
    raise PyMISPUnexpectedResponse(error_msg)
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response (size: 1) from server: 
```

**Comment by Rafiot** [comment]
Thank you for the report!
