### ISSUE TITLE
failed to get data from MISP after upgrade to 2.4.144

### ISSUE THREAD

**Issue by baymax1908** [MISP/PyMISP#755]
OS: Centos 7
MISP: 2.4.144
pymisp: 2.4.144

The script is working fine. After upgrade to MISP 2.4.144. It failed.
Error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 3432, in _check_response
    response_json = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 171, in __init__
    misp_version = self.misp_instance_version
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 242, in misp_instance_version
    return self._check_json_response(response)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 3400, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 3442, in _check_response
    raise PyMISPUnexpectedResponse(error_msg)
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response (size: 3335) from server: <pre class="cake-error"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-trace').style.display = (document.getElementById('cakeErr60c326bd75667-trace').style.display == 'none' ? '' : 'none');"><b>Notice</b> (8)</a>: Undefined index: perm_galaxy_editor [<b>APP/Controller/ServersController.php</b>, line <b>1808</b>]<div id="cakeErr60c326bd75667-trace" class="cake-stack-trace" style="display: none;"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-code').style.display = (document.getElementById('cakeErr60c326bd75667-code').style.display == 'none' ? '' : 'none')">Code</a> <a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-context').style.display = (document.getElementById('cakeErr60c326bd75667-context').style.display == 'none' ? '' : 'none')">Context</a><pre id="cakeErr60c326bd75667-code" class="cake-code-dump" style="display: none;"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_sync'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_sync'</span><span style="color: #007700">],</span></span></code>
<code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_sighting'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_sighting'</span><span style="color: #007700">],</span></span></code>
<span class="code-highlight"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_galaxy_editor'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_galaxy_editor'</span><span style="color: #007700">],</span></span></code></span></pre><pre id="cakeErr60c326bd75667-context" class="cake-context" style="display: none;">$versionArray = array(
        &#039;major&#039; =&gt; (int) 2,
        &#039;minor&#039; =&gt; (int) 4,
        &#039;hotfix&#039; =&gt; (int) 144
)</pre><pre class="stack-trace">ServersController::getVersion() - APP/Controller/ServersController.php, line 1808
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92</pre></div></pre>{"version":"2.4.144","perm_sync":true,"perm_sighting":true,"perm_galaxy_editor":null,"request_encoding":["gzip"]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "new.py", line 11, in <module>
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 181, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (FQDN). Please make sure the API key and the URL are correct (http/https is required): Unexpected response (size: 3335) from server: <pre class="cake-error"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-trace').style.display = (document.getElementById('cakeErr60c326bd75667-trace').style.display == 'none' ? '' : 'none');"><b>Notice</b> (8)</a>: Undefined index: perm_galaxy_editor [<b>APP/Controller/ServersController.php</b>, line <b>1808</b>]<div id="cakeErr60c326bd75667-trace" class="cake-stack-trace" style="display: none;"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-code').style.display = (document.getElementById('cakeErr60c326bd75667-code').style.display == 'none' ? '' : 'none')">Code</a> <a href="javascript:void(0);" onclick="document.getElementById('cakeErr60c326bd75667-context').style.display = (document.getElementById('cakeErr60c326bd75667-context').style.display == 'none' ? '' : 'none')">Context</a><pre id="cakeErr60c326bd75667-code" class="cake-code-dump" style="display: none;"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_sync'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_sync'</span><span style="color: #007700">],</span></span></code>
<code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_sighting'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_sighting'</span><span style="color: #007700">],</span></span></code>
<span class="code-highlight"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'perm_galaxy_editor'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">userRole</span><span style="color: #007700">[</span><span style="color: #DD0000">'perm_galaxy_editor'</span><span style="color: #007700">],</span></span></code></span></pre><pre id="cakeErr60c326bd75667-context" class="cake-context" style="display: none;">$versionArray = array(
        &#039;major&#039; =&gt; (int) 2,
        &#039;minor&#039; =&gt; (int) 4,
        &#039;hotfix&#039; =&gt; (int) 144
)</pre><pre class="stack-trace">ServersController::getVersion() - APP/Controller/ServersController.php, line 1808
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92</pre></div></pre>{"version":"2.4.144","perm_sync":true,"perm_sighting":true,"perm_galaxy_editor":null,"request_encoding":["gzip"]}

**Comment by baymax1908** [comment]
I can get the data by postman. By python, seems it didn't parse the result correctly.

**Comment by Rafiot** [comment]
Yeah, MISP is returning a stacktrace, so PyMISP fails to parse the json. 

@mokaddem @iglocska that's something for you, I think?

**Comment by baymax1908** [comment]
Fixed this issue by changing the getVersion() function to old version.

public function getVersion()
{
if (!$this->userRole['perm_auth']) {
throw new MethodNotAllowedException('This action requires API access.');
}
$versionArray = $this->Server->checkMISPVersion();
$this->set('response', array('version' => $versionArray['major'] . '.' . $versionArray['minor'] . '.' . $versionArray['hotfix'], 'perm_sync' => $this->userRole['perm_sync'], 'perm_sighting' => $this->userRole['perm_sighting']));
$this->set('_serialize', 'response');
}

**Comment by Rafiot** [comment]
The test suite is passing on the github actions so I'm not sure what you're talking about.

**Comment by mokaddem** [comment]
@baymax1908 could you check the diagnostic page in MISP? Especially the database schema diagnostic.
Thanks!
