### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by Pragathi633** [MISP/PyMISP#813]
MISP every time I access list attributes 504 error.
I use pymisp to search attirbutes and it gives 500 error

I increased php memory to 15G 
still have the same problem

**Comment by Rafiot** [comment]
5XX errors are something bad happening server side. If the web interface doesn't work, PyMISP won't either.

You'll need to look at the logs (MISP and webserver) on the machine.

**Comment by paligram** [comment]
so we have the same problem.
web interface is working fine.
this is the error I saw in the logs
Error: [InvalidArgumentException] Restsearch queries using GET and no parameters are not allowed. If you have passed parameters via a JSON body, make sure you use POST requests.

it was working fine and then stopped working

Request URL: /events/restSearch

Stack Trace:

#0 [internal function]: AppController->restSearch()

#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()

#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()

#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()

#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()

result = misp.search (controller='attributes',
                                   category ='Attribution'
                                  timestamp='1d',
                                  category='Network activity')
