### ISSUE TITLE
ssdeep error while instantiating FileObject on Python 3.10.9

### ISSUE THREAD

**Issue by mhpcchaves** [MISP/PyMISP#914]
Hi,

I was testing the following code on Ubuntu 20.04 running Python 3.10.9:

```
#! /usr/bin/env python3

from pymisp import PyMISP, MISPEvent
from pymisp.tools import FileObject
from keys import misp_url, misp_key, misp_verifycert

FILE = 'sample.bin'

# create misp instance
misp = PyMISP(misp_url, misp_key, misp_verifycert)

# create event
my_event = MISPEvent()

my_event.info = f'MISP Sample File Object'
my_event.threat_level_id = 3
my_event.analysis = 0

# add basic information to event
my_event = misp.add_event(event=my_event, pythonify=True)

# add tag to event
misp.tag(my_event, 'tlp:green')

# create misp file object
misp_fobj = FileObject(filepath=FILE)

# add file object to event
my_fobj = misp.add_object(my_event.id, misp_fobj, pythonify=True)
```
The execution of this code produces the following error:
```
Traceback (most recent call last):
  File "./create_file_object.py", line 26, in <module>
    misp_fobj = FileObject(filepath=FILE)
  File "/user/PyMISP/venv/lib/python3.10/site-packages/pymisp/tools/fileobject.py", line 56, in __init__
    self.generate_attributes()
  File "/user/PyMISP/venv/lib/python3.10/site-packages/pymisp/tools/fileobject.py", line 71, in generate_attributes
    self.add_attribute('ssdeep', value=pydeep.hash_buf(self.__data).decode())
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
The PyMISP version is 2.4.168.

This code runs perfectly on Python 3.9.x.

Please, can you take a look at this issue?

Thank you very much.

**Comment by Rafiot** [comment]
can you check the version of pydeep you have installed? It should be `pydeep2` version 0.5.1 

If it is, we will need to check it with @JakubOnderka.

**Comment by mhpcchaves** [comment]
I was using pydeep version 0.4. I've recreated the venv, installed pydeep2 and it worked!

`fileobject.py` has the following code:
```
        if not HAS_PYDEEP:
            logger.warning("Please install pydeep: pip install git+https://github.com/kbandla/pydeep.git")
```
Should this code be updated to point to pydeep2?

Thank's again.

**Comment by Rafiot** [comment]
Absolutely, thanks for noticing it. I removed the reference.
